apiVersion: streaming.sneaksanddata.com/v1
kind: StreamClass
metadata:
  name: {{ template "app.fullname" . }}-v2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamclass.labels" $ | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  apiGroupRef: streaming.sneaksanddata.com
  kindRef: TestStreamDefinitionV2
  apiVersion: v2
  pluralName: teststreamdefinitionv2s
  secretRefs:
    - testSecretRef
